version: '3.3'
services:
  itn-dashboard:
    image: sc-registry.fredhutch.org/itn-dashboard:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.itn-dashboard.rule=Host(`itn-dashboard.fredhutch.org`)"
        - "traefik.http.routers.itn-dashboard-secured.rule=Host(`itn-dashboard.fredhutch.org`)"
        - "traefik.http.routers.itn-dashboard.entrypoints=web,web-secured"
        - "traefik.http.services.itn-dashboard.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.itn-dashboard.tls=true"

networks:
  proxy:
    external: true